/**
 * DEMO / MOCK DATA LAYER
 *
 * When DEMO_MODE=true or when API keys are missing,
 * these fixtures are returned instead of calling TheSportsDB.
 *
 * This lets the UI compile and run without any external credentials.
 */

export const DEMO_MODE =
  process.env.DEMO_MODE === "true" ||
  !process.env.SPORTSDB_API_KEY ||
  process.env.SPORTSDB_API_KEY === "your_sportsdb_api_key";

// ── Mock Events ──────────────────────────────────────────────
export const MOCK_EVENTS = [
  {
    idEvent: "mock-1",
    strEvent: "Manchester City vs Arsenal",
    strLeague: "English Premier League",
    idLeague: "4328",
    strSeason: "2024-2025",
    strHomeTeam: "Manchester City",
    idHomeTeam: "133613",
    strAwayTeam: "Arsenal",
    idAwayTeam: "133604",
    intHomeScore: "2",
    intAwayScore: "1",
    strStatus: "FT",
    strProgress: "",
    dateEvent: new Date().toISOString().split("T")[0],
    strTime: "15:00:00",
    strTimestamp: new Date().toISOString(),
    strThumb: "",
    strSport: "Soccer",
    strVenue: "Etihad Stadium",
    strCity: "Manchester",
    strCountry: "England",
    strLeagueBadge: "https://www.thesportsdb.com/images/media/league/badge/qkx3j81721552903.png",
    strHomeTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png",
    strAwayTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/a1af5r1557005128.png",
    strHomeGoalDetails: "Haaland 23' Rodri 67'",
    strAwayGoalDetails: "Saka 45'",
    strVideo: null,
  },
  {
    idEvent: "mock-2",
    strEvent: "Real Madrid vs Barcelona",
    strLeague: "Spanish La Liga",
    idLeague: "4335",
    strSeason: "2024-2025",
    strHomeTeam: "Real Madrid",
    idHomeTeam: "133600",
    strAwayTeam: "Barcelona",
    idAwayTeam: "133601",
    intHomeScore: null,
    intAwayScore: null,
    strStatus: "NS",
    strProgress: "",
    dateEvent: new Date().toISOString().split("T")[0],
    strTime: "21:00:00",
    strTimestamp: new Date(Date.now() + 3 * 3600000).toISOString(),
    strThumb: "",
    strSport: "Soccer",
    strVenue: "Santiago Bernabéu",
    strCity: "Madrid",
    strCountry: "Spain",
    strLeagueBadge: "https://www.thesportsdb.com/images/media/league/badge/7onmyv1534768460.png",
    strHomeTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/xzqdr11451543765.png",
    strAwayTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/yslnox1519702862.png",
    strHomeGoalDetails: null,
    strAwayGoalDetails: null,
    strVideo: null,
  },
  {
    idEvent: "mock-3",
    strEvent: "PSG vs Lyon",
    strLeague: "French Ligue 1",
    idLeague: "4334",
    strSeason: "2024-2025",
    strHomeTeam: "PSG",
    idHomeTeam: "133603",
    strAwayTeam: "Lyon",
    idAwayTeam: "133636",
    intHomeScore: "1",
    intAwayScore: "0",
    strStatus: "75",
    strProgress: "75",
    dateEvent: new Date().toISOString().split("T")[0],
    strTime: "20:00:00",
    strTimestamp: new Date().toISOString(),
    strThumb: "",
    strSport: "Soccer",
    strVenue: "Parc des Princes",
    strCity: "Paris",
    strCountry: "France",
    strLeagueBadge: "https://www.thesportsdb.com/images/media/league/badge/7onmyv1534768460.png",
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strHomeGoalDetails: "Mbappé 23'",
    strAwayGoalDetails: "",
    strVideo: null,
  },
  {
    idEvent: "mock-4",
    strEvent: "Bahrain Grand Prix",
    strLeague: "Formula 1",
    idLeague: "4370",
    strSeason: "2024",
    strHomeTeam: "Bahrain",
    idHomeTeam: "",
    strAwayTeam: "",
    idAwayTeam: "",
    intHomeScore: null,
    intAwayScore: null,
    strStatus: "NS",
    strProgress: "",
    dateEvent: new Date().toISOString().split("T")[0],
    strTime: "15:00:00",
    strTimestamp: new Date(Date.now() + 6 * 3600000).toISOString(),
    strThumb: "",
    strSport: "Motorsport",
    strVenue: "Bahrain International Circuit",
    strCity: "Sakhir",
    strCountry: "Bahrain",
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strHomeGoalDetails: null,
    strAwayGoalDetails: null,
    strVideo: null,
  },
  {
    idEvent: "mock-5",
    strEvent: "Brazil vs Italy (VNL)",
    strLeague: "VNL Men",
    idLeague: "4952",
    strSeason: "2024",
    strHomeTeam: "Brazil",
    idHomeTeam: "mock-br-vb",
    strAwayTeam: "Italy",
    idAwayTeam: "mock-it-vb",
    intHomeScore: "3",
    intAwayScore: "1",
    strStatus: "FT",
    strProgress: "",
    dateEvent: new Date().toISOString().split("T")[0],
    strTime: "18:00:00",
    strTimestamp: new Date().toISOString(),
    strThumb: "",
    strSport: "Volleyball",
    strVenue: "Arena Carioca",
    strCity: "Rio de Janeiro",
    strCountry: "Brazil",
    strLeagueBadge: null,
    strHomeTeamBadge: null,
    strAwayTeamBadge: null,
    strHomeGoalDetails: null,
    strAwayGoalDetails: null,
    strVideo: null,
  },
];

export const MOCK_EVENT_DETAIL = {
  ...MOCK_EVENTS[0],
  stats: [
    { strStat: "Possession", intHome: "58", intAway: "42" },
    { strStat: "Shots", intHome: "15", intAway: "8" },
    { strStat: "Shots on Target", intHome: "6", intAway: "3" },
    { strStat: "Corners", intHome: "7", intAway: "4" },
    { strStat: "Fouls", intHome: "10", intAway: "14" },
    { strStat: "Yellow Cards", intHome: "1", intAway: "2" },
    { strStat: "Passes", intHome: "542", intAway: "391" },
  ],
  timeline: [
    { idEvent: "mock-1", strTimeline: "23", strTimelineDetail: "Goal", strTeam: "Manchester City", strAction: "Goal", strPlayer: "Erling Haaland", strPlayer2: "Kevin De Bruyne", intTime: "23" },
    { idEvent: "mock-1", strTimeline: "45", strTimelineDetail: "Goal", strTeam: "Arsenal", strAction: "Goal", strPlayer: "Bukayo Saka", strPlayer2: "Martin Ødegaard", intTime: "45" },
    { idEvent: "mock-1", strTimeline: "55", strTimelineDetail: "Yellow Card", strTeam: "Arsenal", strAction: "Yellow Card", strPlayer: "Thomas Partey", strPlayer2: "", intTime: "55" },
    { idEvent: "mock-1", strTimeline: "67", strTimelineDetail: "Goal", strTeam: "Manchester City", strAction: "Goal", strPlayer: "Rodrigo", strPlayer2: "Phil Foden", intTime: "67" },
  ],
  lineup: [
    { idPlayer: "p1", strPlayer: "Ederson", strTeam: "Manchester City", strPosition: "GK", intSquadNumber: "31", strHome: "1" },
    { idPlayer: "p2", strPlayer: "Kyle Walker", strTeam: "Manchester City", strPosition: "DEF", intSquadNumber: "2", strHome: "1" },
    { idPlayer: "p3", strPlayer: "Rúben Dias", strTeam: "Manchester City", strPosition: "DEF", intSquadNumber: "3", strHome: "1" },
    { idPlayer: "p4", strPlayer: "Manuel Akanji", strTeam: "Manchester City", strPosition: "DEF", intSquadNumber: "25", strHome: "1" },
    { idPlayer: "p5", strPlayer: "Rodri", strTeam: "Manchester City", strPosition: "MID", intSquadNumber: "16", strHome: "1" },
    { idPlayer: "p6", strPlayer: "Kevin De Bruyne", strTeam: "Manchester City", strPosition: "MID", intSquadNumber: "17", strHome: "1" },
    { idPlayer: "p7", strPlayer: "Erling Haaland", strTeam: "Manchester City", strPosition: "FWD", intSquadNumber: "9", strHome: "1" },
    { idPlayer: "p8", strPlayer: "David Raya", strTeam: "Arsenal", strPosition: "GK", intSquadNumber: "22", strHome: "0" },
    { idPlayer: "p9", strPlayer: "Ben White", strTeam: "Arsenal", strPosition: "DEF", intSquadNumber: "4", strHome: "0" },
    { idPlayer: "p10", strPlayer: "William Saliba", strTeam: "Arsenal", strPosition: "DEF", intSquadNumber: "12", strHome: "0" },
    { idPlayer: "p11", strPlayer: "Bukayo Saka", strTeam: "Arsenal", strPosition: "MID", intSquadNumber: "7", strHome: "0" },
    { idPlayer: "p12", strPlayer: "Martin Ødegaard", strTeam: "Arsenal", strPosition: "MID", intSquadNumber: "8", strHome: "0" },
  ],
};

export const MOCK_TEAM = {
  id: "133613",
  name: "Manchester City",
  sport: "Soccer",
  league: { id: "4328", name: "English Premier League" },
  badge: "https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png",
  stadium: "Etihad Stadium",
  city: "Manchester",
  country: "England",
  formedYear: "1880",
  description:
    "Manchester City Football Club is an English football club based in Manchester that competes in the Premier League, the top flight of English football.",
  website: "www.mancity.com",
  players: [
    { idPlayer: "p1", strPlayer: "Ederson", strPosition: "GK", strNumber: "31", strThumb: null },
    { idPlayer: "p2", strPlayer: "Kyle Walker", strPosition: "DEF", strNumber: "2", strThumb: null },
    { idPlayer: "p3", strPlayer: "Rúben Dias", strPosition: "DEF", strNumber: "3", strThumb: null },
    { idPlayer: "p4", strPlayer: "Manuel Akanji", strPosition: "DEF", strNumber: "25", strThumb: null },
    { idPlayer: "p5", strPlayer: "Rodri", strPosition: "MID", strNumber: "16", strThumb: null },
    { idPlayer: "p6", strPlayer: "Kevin De Bruyne", strPosition: "MID", strNumber: "17", strThumb: null },
    { idPlayer: "p7", strPlayer: "Erling Haaland", strPosition: "FWD", strNumber: "9", strThumb: null },
    { idPlayer: "p8", strPlayer: "Phil Foden", strPosition: "MID", strNumber: "47", strThumb: null },
  ],
  nextEvents: [MOCK_EVENTS[1]],
  prevEvents: [MOCK_EVENTS[0]],
};

export const MOCK_PLAYER = {
  id: "34145937",
  name: "Erling Haaland",
  teamId: "133613",
  teamName: "Manchester City",
  sport: "Soccer",
  position: "FWD",
  nationality: "Norwegian",
  dateBorn: "2000-07-21",
  height: "194 cm",
  weight: "88 kg",
  number: "9",
  thumb: "https://www.thesportsdb.com/images/media/player/thumb/haaland.jpg",
  description:
    "Erling Braut Haaland is a Norwegian professional footballer who plays as a striker for Premier League club Manchester City and the Norway national team.",
};

export const MOCK_COMPETITION = {
  id: "4328",
  name: "English Premier League",
  sport: "Soccer",
  country: "England",
  badge: "https://www.thesportsdb.com/images/media/league/badge/qkx3j81721552903.png",
  currentSeason: "2024-2025",
  description: "The Premier League is the top level of the English football league system.",
  teams: [
    { idTeam: "133613", strTeam: "Manchester City", strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png" },
    { idTeam: "133604", strTeam: "Arsenal", strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/a1af5r1557005128.png" },
    { idTeam: "133602", strTeam: "Liverpool", strTeamBadge: "https://www.thesportsdb.com/images/media/team/badge/uvtvqy1512151078.png" },
    { idTeam: "133616", strTeam: "Chelsea", strTeamBadge: null },
    { idTeam: "133612", strTeam: "Manchester United", strTeamBadge: null },
    { idTeam: "133619", strTeam: "Tottenham", strTeamBadge: null },
  ],
  nextEvents: [MOCK_EVENTS[1]],
  prevEvents: [MOCK_EVENTS[0]],
};

export const MOCK_SEARCH_RESULTS = [
  { type: "team", id: "133613", name: "Manchester City", badge: "https://www.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png", subtitle: "Soccer • England", href: "/team/133613" },
  { type: "team", id: "133604", name: "Arsenal", badge: "https://www.thesportsdb.com/images/media/team/badge/a1af5r1557005128.png", subtitle: "Soccer • England", href: "/team/133604" },
  { type: "player", id: "34145937", name: "Erling Haaland", badge: null, subtitle: "FWD • Manchester City", href: "/player/34145937" },
  { type: "competition", id: "4328", name: "English Premier League", badge: "https://www.thesportsdb.com/images/media/league/badge/qkx3j81721552903.png", subtitle: "Soccer • England", href: "/competition/4328" },
];

export const MOCK_FANTASY_PLAYERS = [
  { idPlayer: "p1", strPlayer: "Ederson",          strTeam: "Manchester City", strPosition: "GK",  price: 5.5 },
  { idPlayer: "p8", strPlayer: "David Raya",        strTeam: "Arsenal",         strPosition: "GK",  price: 5.0 },
  { idPlayer: "p2", strPlayer: "Kyle Walker",       strTeam: "Manchester City", strPosition: "DEF", price: 5.0 },
  { idPlayer: "p3", strPlayer: "Rúben Dias",        strTeam: "Manchester City", strPosition: "DEF", price: 6.0 },
  { idPlayer: "p9", strPlayer: "Ben White",         strTeam: "Arsenal",         strPosition: "DEF", price: 5.5 },
  { idPlayer: "p10",strPlayer: "William Saliba",    strTeam: "Arsenal",         strPosition: "DEF", price: 5.5 },
  { idPlayer: "p5", strPlayer: "Rodri",             strTeam: "Manchester City", strPosition: "MID", price: 6.5 },
  { idPlayer: "p6", strPlayer: "Kevin De Bruyne",   strTeam: "Manchester City", strPosition: "MID", price: 9.5 },
  { idPlayer: "p8b",strPlayer: "Phil Foden",        strTeam: "Manchester City", strPosition: "MID", price: 8.0 },
  { idPlayer: "p11",strPlayer: "Bukayo Saka",       strTeam: "Arsenal",         strPosition: "MID", price: 9.0 },
  { idPlayer: "p12",strPlayer: "Martin Ødegaard",   strTeam: "Arsenal",         strPosition: "MID", price: 8.5 },
  { idPlayer: "p7", strPlayer: "Erling Haaland",    strTeam: "Manchester City", strPosition: "FWD", price: 14.0 },
  { idPlayer: "p13",strPlayer: "Gabriel Jesus",     strTeam: "Arsenal",         strPosition: "FWD", price: 7.5 },
  { idPlayer: "p14",strPlayer: "Marcus Rashford",   strTeam: "Manchester United",strPosition:"FWD", price: 7.0 },
  { idPlayer: "p15",strPlayer: "Dominic Solanki",   strTeam: "Liverpool",       strPosition: "FWD", price: 7.0 },
];

export const MOCK_F1_DRIVERS = [
  { id: "f1-1", name: "Max Verstappen", teamId: "rb", teamName: "Red Bull Racing", teamBadge: "", number: "1", nationality: "Netherlands", thumb: "", dateBorn: "1997-09-30", status: "Active", position: "Driver" },
  { id: "f1-2", name: "Sergio Perez", teamId: "rb", teamName: "Red Bull Racing", teamBadge: "", number: "11", nationality: "Mexico", thumb: "", dateBorn: "1990-01-26", status: "Active", position: "Driver" },
  { id: "f1-3", name: "Lewis Hamilton", teamId: "mer", teamName: "Mercedes", teamBadge: "", number: "44", nationality: "United Kingdom", thumb: "", dateBorn: "1985-01-07", status: "Active", position: "Driver" },
  { id: "f1-4", name: "George Russell", teamId: "mer", teamName: "Mercedes", teamBadge: "", number: "63", nationality: "United Kingdom", thumb: "", dateBorn: "1998-02-15", status: "Active", position: "Driver" },
  { id: "f1-5", name: "Charles Leclerc", teamId: "fer", teamName: "Ferrari", teamBadge: "", number: "16", nationality: "Monaco", thumb: "", dateBorn: "1997-10-16", status: "Active", position: "Driver" },
  { id: "f1-6", name: "Carlos Sainz", teamId: "fer", teamName: "Ferrari", teamBadge: "", number: "55", nationality: "Spain", thumb: "", dateBorn: "1994-09-01", status: "Active", position: "Driver" },
  { id: "f1-7", name: "Lando Norris", teamId: "mcl", teamName: "McLaren", teamBadge: "", number: "4", nationality: "United Kingdom", thumb: "", dateBorn: "1999-11-13", status: "Active", position: "Driver" },
  { id: "f1-8", name: "Oscar Piastri", teamId: "mcl", teamName: "McLaren", teamBadge: "", number: "81", nationality: "Australia", thumb: "", dateBorn: "2001-04-06", status: "Active", position: "Driver" },
  { id: "f1-9", name: "Fernando Alonso", teamId: "ast", teamName: "Aston Martin", teamBadge: "", number: "14", nationality: "Spain", thumb: "", dateBorn: "1981-07-29", status: "Active", position: "Driver" },
  { id: "f1-10", name: "Lance Stroll", teamId: "ast", teamName: "Aston Martin", teamBadge: "", number: "18", nationality: "Canada", thumb: "", dateBorn: "1998-10-29", status: "Active", position: "Driver" },
  { id: "f1-11", name: "Pierre Gasly", teamId: "alp", teamName: "Alpine", teamBadge: "", number: "10", nationality: "France", thumb: "", dateBorn: "1996-02-07", status: "Active", position: "Driver" },
  { id: "f1-12", name: "Esteban Ocon", teamId: "alp", teamName: "Alpine", teamBadge: "", number: "31", nationality: "France", thumb: "", dateBorn: "1996-09-17", status: "Active", position: "Driver" },
  { id: "f1-13", name: "Yuki Tsunoda", teamId: "rb2", teamName: "RB", teamBadge: "", number: "22", nationality: "Japan", thumb: "", dateBorn: "2000-05-11", status: "Active", position: "Driver" },
  { id: "f1-14", name: "Daniel Ricciardo", teamId: "rb2", teamName: "RB", teamBadge: "", number: "3", nationality: "Australia", thumb: "", dateBorn: "1989-07-01", status: "Active", position: "Driver" },
  { id: "f1-15", name: "Alexander Albon", teamId: "wil", teamName: "Williams", teamBadge: "", number: "23", nationality: "Thailand", thumb: "", dateBorn: "1996-03-23", status: "Active", position: "Driver" },
  { id: "f1-16", name: "Logan Sargeant", teamId: "wil", teamName: "Williams", teamBadge: "", number: "2", nationality: "United States", thumb: "", dateBorn: "2000-12-31", status: "Active", position: "Driver" },
  { id: "f1-17", name: "Valtteri Bottas", teamId: "sau", teamName: "Kick Sauber", teamBadge: "", number: "77", nationality: "Finland", thumb: "", dateBorn: "1989-08-28", status: "Active", position: "Driver" },
  { id: "f1-18", name: "Zhou Guanyu", teamId: "sau", teamName: "Kick Sauber", teamBadge: "", number: "24", nationality: "China", thumb: "", dateBorn: "1999-05-30", status: "Active", position: "Driver" },
  { id: "f1-19", name: "Kevin Magnussen", teamId: "has", teamName: "Haas", teamBadge: "", number: "20", nationality: "Denmark", thumb: "", dateBorn: "1992-10-05", status: "Active", position: "Driver" },
  { id: "f1-20", name: "Nico Hulkenberg", teamId: "has", teamName: "Haas", teamBadge: "", number: "27", nationality: "Germany", thumb: "", dateBorn: "1987-08-19", status: "Active", position: "Driver" },
];
